let
  -- raise an exception by divided 0
  main = let x = 1 / 0 in x
in main
